version: "3.8"

services:
    ffa: 
        image: filz26/ffa:latest
        ports: 
            - 2500
        restart: always
        environment: 
            VIRTUAL_HOST: ffa.filipedev.xyz
            LETSENCRYPT_HOST: ffa.filipedev.xyz
            LETSENCRYOT_EMAIL: filipefig26@gmail.com

networks:
    default:
        external: 
            name: nginx-proxy